### ISSUE TITLE
m3u8 url not found

### ISSUE THREAD

**Issue by thekkiller** [MacielG1/VodRecovery#21]
recently i cloned my windows to my ssd since then it does not find the m3u8 url of any vods, i tried with twitch recovery and it does recover the same vod in there.
tried reinstalling python and the dependencies it does not give me any error just the red  "✖  Unable to recover the video!"

edit:tried with version 1.0.2 which is the oldest and it worked as well i have no idea what is going on

**Comment by MacielG1** [comment]
That's odd. What's the complete output, other than the "Unable to recover" line? Maybe try installing the dependencies manually by opening the VodRecovery folder in the terminal and running the command: `pip install -r lib/requirements.txt` and see if there are any errors

**Comment by thekkiller** [comment]
tried those command like you said and its just a bunch of requirements already satisfied that probably means i already got it installed
Retrieving datetime from Twitchtracker...
Datetime: 2024-10-19 03:33:40

> Searching for M3U8 URL...
> Searching 1020/1020 URLs
> Unable to recover! Trying alternate sources...
> 
> Retrieving datetime from Sullygnome...
> Opening Sullygnome with browser...
> C:\Users\username\Desktop\VodRecovery-1.3.3\vod_recovery.py:1256: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
> and fails to parse leap day. The default behavior will change in Python 3.15
> to either always raise an exception or to use a different default year (TBD).
> To avoid trouble, add a specific year to the input & format.
> See https://github.com/python/cpython/issues/70647.
>   formatted_stream_date = datetime.strptime(modified_stream_date, "%A %d %B %I:%M%p").strftime("%m-%d %H:%M:%S")
> Datetime: 2024-10-19 03:33:00
> 
> Searching for M3U8 URL...
> Searching 1020/1020 URLs
> Retrieving datetime from Streamscharts...
> Opening Streamscharts with browser...
> Datetime: 2024-10-19 03:33:00
> 
> ✖  Unable to recover the video!

thats the whole thing, now that i tried again with 1.2.6(which is the latest version that worked i tried 1.2.9 and didnt work i also skipped down 1.2.8 and 1.2.7 so i dont know if those works) i see that this parsing dates problem does not happend in 1.2.6 but it does happend in the newest version maybe that could be the problem, other than that all seems to work
