### ISSUE TITLE
well couldn't recover this vod even though its just 20 days old

### ISSUE THREAD

**Issue by Drag111** [MacielG1/VodRecovery#22]
it showed this 

Enter Twitchtracker/Streamscharts/Sullygnome/Twitch URL: https://twitchtracker.com/flexiejayanime/streams/39375839812
Checking flexiejayanime VOD ID: 39375839812

Retrieving datetime from Twitchtracker...
Datetime: 2024-09-28 14:06:25

Searching for M3U8 URL...
Searching 1020/1020 URLs
Unable to recover! Trying alternate sources...

Retrieving datetime from Sullygnome...
Opening Sullygnome with browser...

Retrieving datetime from Streamscharts...
Opening Streamscharts with browser...

✖  Unable to recover the video!****

can you help me with this or it cant be recovered?

**Comment by MacielG1** [comment]
Unfortunately, no. If the VOD was fully deleted from Twitch servers, there’s no way to recover it. But you could still try checking YouTube or StreamRecorder to see if it was recorded
