### ISSUE TITLE
Open in vlc broken on linux due to wrong slashes in filepath.

### ISSUE THREAD

**Issue by winneratwin** [MacielG1/VodRecovery#23]
when opening a file in vlc on linux the following line [2227](https://github.com/MacielG1/VodRecovery/blob/556e05c0946874806e3f9ffee2c0bca75a4b5135/vod_recovery.py#L2227)
`
                subprocess.Popen([vlc_location, link.replace("/", "\\")])
`
leads to an invalid location being passed to vlc `cannot open file /path/to/VodRecovery/\home\username\Downloads\channel-stream_id.m3u8 (No such file or directory)`

removing the replace fixes it for linux but probably breaks it for windows.

**Comment by MacielG1** [comment]
Thanks! It'll be fixed in the next update
