### ISSUE TITLE
Filename is wrapped in "'" on linux systems.

### ISSUE THREAD

**Issue by winneratwin** [MacielG1/VodRecovery#26]
The code at https://github.com/MacielG1/VodRecovery/blob/3482b635d5707e9de6dab59e8311cc117485192f/vod_recovery.py#L1976-L1977 incorrectly applies quotes to the name of the file leading to a filepath of:

```
output_filename:  'twitch_name - yyyy-mm-dd - [111111111111].mp4'
output_path:  /home/user/Downloads/'twitch_name - yyyy-mm-dd - [111111111111].mp4'
```
vs 
```
output_filename:  twitch_name - yyyy-mm-dd - [111111111111].mp4
output_path:  /home/user/Downloads/twitch_name - yyyy-mm-dd - [111111111111].mp4
```
without it.

This leads to a file with the extension `.mp4'`.

**Comment by MacielG1** [comment]
Thanks for letting me know. I've pushed the new changes. If you want to test them, you can clone the repo

**Comment by winneratwin** [comment]
Fixed.
