### ISSUE TITLE
VodRecovery-1.3.4  Requested output format 'ts' is not known

### ISSUE THREAD

**Issue by Irene75b** [MacielG1/VodRecovery#27]
Requested output format 'ts' is not known.
[out#0 @ 000001d74b52ed80] Error initializing the muxer for E:\TWITCH VOD\sora629 - 2024-10-18 - [44931766411].ts: Invalid argument
Error opening output file E:\TWITCH VOD\sora629 - 2024-10-18 - [44931766411].ts.
Error opening output files: Invalid argument

✗ Failed to download Vod: sora629 - 2024-10-18 - [44931766411].ts

**Comment by Irene75b** [comment]
1.3.2 is work
1.3.4 not work

**Comment by MacielG1** [comment]
Latest version should fix this issue, thanks for warning me!
