### ISSUE TITLE
Just FYI.... "Unable to recover! Trying alternate sources..." message

### ISSUE THREAD

**Issue by MikeyOnline2** [MacielG1/VodRecovery#28]
Hi, I'm not sure if it's a bug... Just FYI.
When I try to download a vod it takes a few seconds: installing drivers the first time, opening browsers etc.
Then it comes back with: "Unable to recover! Trying alternate sources..."
It does it every time. But eventually everything works fine, it only takes a few seconds. I thought I'd let you know.
See screenshot:
<img width="433" alt="2024-10-27_02-45-09" src="https://github.com/user-attachments/assets/768a42f1-7a35-40d2-9159-7bea10ef440f">

**Comment by MacielG1** [comment]
It’s intentional. It wasn’t able to recover with the original URL, so it tries other websites. I can update the output message to be clearer in a future update, perhaps to something like: 'Unable to recover with the original URL! Trying alternate sources..."
