### ISSUE TITLE
An error occurred: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by momtezysf** [MacielG1/VodRecovery#29]
I installed Python but when I open the "install_dependencies" file it gives me this error: Installing dependencies...
An error occurred: [Errno 2] No such file or directory: 'C:\\Users\\momte\\AppData\\Local\\Temp\\54dc0f47-107b-4949-b491-eb21befa7e8b_VodRecovery-1.3.5.zip.e8b\\VodRecovery-1.3.5\\lib\\requirements.txt'

Can you help me please

![Capture d’écran 2024-10-27 113539](https://github.com/user-attachments/assets/2a715d17-630b-4a51-93b1-6234609bed99)

**Comment by MacielG1** [comment]
It looks like you're running the script from the zip file, try extracting it first. If that doesn't work, download VodRecovery to a different folder, avoiding the folder shown in the error
