### ISSUE TITLE
Unavailable Twitchtracker  Sullygnome Streamscharts Looking for M3U8

### ISSUE THREAD

**Issue by Irene75b** [MacielG1/VodRecovery#30]
![螢幕擷取畫面 2024-11-02 172744](https://github.com/user-attachments/assets/980c71f1-0f68-4e52-bc2b-055a67049faf)

**Comment by Irene75b** [comment]
But there was the original live broadcast

https://www.twitch.tv/videos/2278255189?filter=archives&sort=time

**Comment by Irene75b** [comment]
You can see the VOD on her channel.
But can't find M3U8 URL using Twitchtracker Sullygnome Streamscharts.

**Comment by MacielG1** [comment]
@Irene75b You can just paste the direct Twitch URL instead of one of the three websites

**Comment by Irene75b** [comment]
Of course I knew to just post the TWITCH URL.
I mean, did TWITCH change something so that it can't find the M3U8 URL?

**Comment by MacielG1** [comment]
It's working when I try it

Enter Twitchtracker/Streamscharts/Sullygnome/Twitch URL: https://www.twitch.tv/videos/2278255189?filter=archives&sort=time

✓ Found URL: https://d3vd9lfkzbru3h.cloudfront.net/5f7868355023e40efbc7_sandyhsu_41668711303_1729170244/chunked/index-dvr.m3u8

Video contains muted segments
C:\Downloads\sandyhsu_41668711303.m3u8 has been unmuted!

**Comment by Irene75b** [comment]
sorry can you try this URL?
https://twitchtracker.com/sandyhsu/streams/41692234599

is working?

**Comment by Irene75b** [comment]
i try this url
https://twitchtracker.com/sora629/streams/44974646523

sometime is work 
sometime not work
i dont know why.......

**Comment by MacielG1** [comment]
if the url doesn't work, you can try setting the values manually, by using the manual mode

**Comment by MacielG1** [comment]
No, I meant use the Manual Recovery option which is the number 2, then type Streamer name, Stream Id which is the same as in the twitch tracker url and then the datetime

**Comment by Demon1342** [comment]
This issue seems to be fixed in version 1.3.6
