### ISSUE TITLE
Unable to recover very recently deleted VOD

### ISSUE THREAD

**Issue by Jumkox** [MacielG1/VodRecovery#31]
VOD was deleted about an hour ago, still have the twitch link: https://www.twitch.tv/videos/2298791289
https://sullygnome.com/channel/demolition_d/stream/42746217966

Tried manual too, made sure the time was UTC, all that, didn't recover. I figure it's something I'm somehow fucking up, but I'm pretty sure it's just gone. Still, if someone could help me out, I'd appreciate it.

**Comment by MacielG1** [comment]
The VOD has probably already been removed from Twitch's servers, but you could still try finding it on streamrecorder.io

**Comment by Jumkox** [comment]
Oh damn,  yeah it's deleted but it is on that site. Like bits and pieces of it, almost the whole thing actually. Thanks
