### ISSUE TITLE
✖  Unable to recover the video!

### ISSUE THREAD

**Issue by wnase** [MacielG1/VodRecovery#32]
I can't recover this vod for some reason even though it's very recent, if someone can try and tell me if it's only me : 
https://twitchtracker.com/superconeriii/streams/52472086605

Thank you !

**Comment by MacielG1** [comment]
I'm not sure why you were unable to recover. What was the output?
Here's the M3U8: https://d1m7jfoe9zdc1j.cloudfront.net/4eb1038febe3f1914cc6_superconeriii_52472086605_1732224392/chunked/index-dvr.m3u8

**Comment by wnase** [comment]
It tells me that they don't find the datatime, and when i put it manually, it tells me they didn't find it, at first the program was perfectly working (like a week ago), but lately i can't seem to recover a lot of vods for some reason, Thank you so much for the link !

**Comment by wnase** [comment]
It tells me that they don't find the datatime, and when i put it manually, it tells me they didn't find it, at first the program was perfectly working (like a week ago), but lately i can't seem to recover a lot of vods for some reason, Thank you so much for the link !
