### ISSUE TITLE
Cant download section of longer VODs with a start date past 24 hours

### ISSUE THREAD

**Issue by jonas1015119** [MacielG1/VodRecovery#33]
I'm downloading a 48 hour vod in 8 hour sections (from an M3U8 Link) and sections starting past the 24 hour mark will not download, the file stays at 48 bytes in size, the timer next to the progress bar stays at 00:00. I'm assuming this is ffmpeg related?

Starting at the 24 hour mark works (i.e. "-ss "24:00:00 -to 32:00:00", anything after like 32-40 hours does not.

example command: 
Command: ffmpeg -protocol_whitelist file,http,https,tcp,tls -hide_banner -ss 32:00:00 -to 40:00:00 -i https://d2nvs31859zcd8.cloudfront.net/f75e1e9346738b0c6398_billzo_45054375787_1732304140/chunked/index-dvr.m3u8 -c copy -f mp4 -y D:\Downloads\billzo - [45054375787] - 32.00.00 - 40.00.00.mp4

**Comment by MacielG1** [comment]
This is an FFmpeg issue, sometimes it can't handleM3U8 streams that are very long
